### PR TITLE
Fixes problems with 2 carousels

### PR DESCRIPTION
**Pull request by mi2oon**
#7 I had the same error with 2 or more carousels. Options from last instance seems to get inherited if you don't create an empty object to extend with.

### CODE REVIEW

**Comment by mi2oon** [comment]
@gijsroge Hope it's alright that I didn't build or bump the version. Let me know if you want me to :smiley:

**Comment by David-Zolv** [comment]
+1 please merge this in

**Comment by ollywenn** [comment]
+1 Yeah - what @DaveOMac said... please.

**Comment by ollywenn** [comment]
Thanks, man.

**Pull request merged**
